sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.4
  - 2.4.0
  - ruby-head
env:
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.4"
matrix:
  allow_failures:
    - rvm: ruby-head

bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem update bundler

after_success:
  - bundle exec codeclimate-test-reporter
