sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.5
  - 2.4.1
  - 2.5.0
  - 2.6.0
env:
  - RAILS_VERSION=5.0.0
  - RAILS_VERSION=5.1.4
matrix:
  allow_failures:
    - rvm: 2.6.0
  exclude:
    - rvm: 2.5.0
      env: RAILS_VERSION=5.0.0
    - rvm: 2.6.0
      env: RAILS_VERSION=5.0.0

cache: bundler
